package com.skupsie.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF7829E5)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFECDCFF)
val md_theme_light_onPrimaryContainer = Color(0xFF270058)
val md_theme_light_secondary = Color(0xFF8C31B9)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF6D9FF)
val md_theme_light_onSecondaryContainer = Color(0xFF310048)
val md_theme_light_tertiary = Color(0xFF6C4EA2)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEBDCFF)
val md_theme_light_onTertiaryContainer = Color(0xFF270058)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF121212)
val md_theme_light_surface = Color(0xFFF8FDFF)
val md_theme_light_onSurface = Color(0xFF001F25)
val md_theme_light_surfaceVariant = Color(0xFFE8E0EB)
val md_theme_light_onSurfaceVariant = Color(0xFF49454E)
val md_theme_light_outline = Color(0xFF7A757F)
val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
val md_theme_light_inverseSurface = Color(0xFF00363F)
val md_theme_light_inversePrimary = Color(0xFFD5BBFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF7829E5)
val md_theme_light_outlineVariant = Color(0xFFCBC4CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFD5BBFF)
val md_theme_dark_onPrimary = Color(0xFF41008B)
val md_theme_dark_primaryContainer = Color(0xFF5E00C1)
val md_theme_dark_onPrimaryContainer = Color(0xFFECDCFF)
val md_theme_dark_secondary = Color(0xFFE9B3FF)
val md_theme_dark_onSecondary = Color(0xFF510074)
val md_theme_dark_secondaryContainer = Color(0xFF71099F)
val md_theme_dark_onSecondaryContainer = Color(0xFFF6D9FF)
val md_theme_dark_tertiary = Color(0xFFD4BBFF)
val md_theme_dark_onTertiary = Color(0xFF3D1C70)
val md_theme_dark_tertiaryContainer = Color(0xFF543588)
val md_theme_dark_onTertiaryContainer = Color(0xFFEBDCFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF121212)
val md_theme_dark_onBackground = Color(0xFFFFFFFF)
val md_theme_dark_surface = Color(0xFF001F25)
val md_theme_dark_onSurface = Color(0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(0xFF49454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFCBC4CF)
val md_theme_dark_outline = Color(0xFF958E99)
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(0xFF7829E5)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFD5BBFF)
val md_theme_dark_outlineVariant = Color(0xFF49454E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFAC07F2)
val progressBarColor = Color(0xFF97CF56)
val premiumColor = Color(0xFFF6B704)
val light_progressBarColor = Color(0xFF3F6A00)
val light_onprogressBarColor = Color(0xFFFFFFFF)
val light_progressBarColorContainer = Color(0xFFB9F476)
val light_onprogressBarColorContainer = Color(0xFF0F2000)
val dark_progressBarColor = Color(0xFF9ED75D)
val dark_onprogressBarColor = Color(0xFF1E3700)
val dark_progressBarColorContainer = Color(0xFF2E4F00)
val dark_onprogressBarColorContainer = Color(0xFFB9F476)
val light_premiumColor = Color(0xFF7A5900)
val light_onpremiumColor = Color(0xFFFFFFFF)
val light_premiumColorContainer = Color(0xFFFFDEA1)
val light_onpremiumColorContainer = Color(0xFF261900)
val dark_premiumColor = Color(0xFFFCBC11)
val dark_onpremiumColor = Color(0xFF402D00)
val dark_premiumColorContainer = Color(0xFF5C4200)
val dark_onpremiumColorContainer = Color(0xFFFFDEA1)

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val DarkPurple = Color(0xFF4850EE)
val LightPurple = Color(0xFF8B90F3)

val PurpleGradient1 = Color(0xFFAC07F2)
val PurpleGradient2 = Color(0xFF6F039D)